### PR TITLE
fix: disable only col2row feature

### LINKED ISSUE #3: Enable all other default features is row2col is set
https://github.com/HaoboGu/rmkit/blob/master/src/main.rs#L439

When the row2col is set, the default features is set to false. Then the other default features should be enabled manually. 

Or, adding configurations for all other cargo features? when doing cloud compilation, the rmkit could decide which feature should be enabled by the keyboard.toml

### PR DESCRIPTION
**Pull request by pcasotti**
Closes #3

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -436,7 +440,11 @@ fn copy_dir_recursive(src: &Path, dest: &Path) -> io::Result<()> {
 ///
 /// # Returns
 /// * `Result<(), String>` - 成功返回 Ok，失败返回 Err
-fn disable_rmk_default_feature(target_dir: &PathBuf) -> Result<(), String> {
+fn disable_rmk_default_feature(
+    target_dir: &PathBuf,
+    metadata: &Metadata,
+    feature: &str,
```
Comment (HaoboGu) [inline src/main.rs:446]: This feature is the feature that to be disabled? Should it be a vector?

**Comment by HaoboGu** [comment]
thanks a lot!
